#! /bin/bash
# pkill polybar
#!/bin/bash
#АВТОСТАРТ
sxhkd &
flameshot &
#numlockx &
nitrogen --restore &
#polybar example &
eww kill && eww daemon
eww open bar-left
eww open bar-right
eww open bar-center
picom &
xsetroot -cursor_name left_ptr &
conky &
#steam &

#ВОРКСПЕЙСЫ
bspc monitor -d 1 2 3 4 5 6



#РАМКИ И ГАПСЫ
bspc config border_width        0
bspc config window_gap          8

bspc config normal_border_color "#22283e"
bspc config active_border_color "#22283e"
bspc config focused_border_color "#1f2e63"

#ЦВЕТ ПРОСТРАНСТВА ПРИ ВЫБОРЕ ПОЛОЖЕНИЯ НОВОГО ОКНА
bspc config presel_feedback_color "#ffffff"



#КОФИЦИЕНТ РАЗДЕЛЕНИЯ, СКОЛЬКО ПРОЦЕНТОВ ОСТАНЕТСЯ ОТ РОДИТЕЛЬСКОГО ОКНА ПРИ ОТКРЫТИИ НОВОГО
bspc config split_ratio          0.5
#ФОКУС ОКНА НАВЕДЕНИЕМ КУРСОРА
bspc config focus_follows_pointer true
bspc config pointer_modifier	super

#РЕЖИМ МОНОКЛЯ КОГДА ОТКРЫТО ОДНО ОКНО
bspc config single_monocle	     false

#ОТКЛЮЧЕНИЕ ГАПСОВ РАМОК И ОТСТУПОВ КОГДА ОТКРЫТО ОДНО ОКНО
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config paddingless_monocle	 true


#СХЕМЫ СОГЛАСНО КОТОРЫМ БУДУТ ОТКРЫВАТСЯ ОКНА
#bspc config automatic_scheme	spiral


#ПРАВИЛА ОКОН
bspc rule -a Opera desktop='^1'
bspc rule -a TelegramDesktop desktop='^5'
bspc rule -a dmenu rectangle=900x22+610+90
bspc rule -a Zoom desktop="^6"
bspc rule -a discord desktop="^7"
bpsc rule -a steam desktop="^3"
bspc rule -a GLava state=floating rectangle=1500x100
/usr/lib/notification-daemon-1.0/notification-daemon &
#glava --entry=rc3.glsl --desktop &
#glava --entry=rc.glsl --desktop &
